<a href="https://colab.research.google.com/github/gowtham777y/Salary-predictor/blob/main/Salary_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [12]:
df=pd.read_csv("Salary_Data.csv")

In [18]:
x=df.iloc[:,0].values.reshape(-1,1)
y=df.iloc[:,1].values.reshape(-1,1)

In [22]:
from sklearn.model_selection import train_test_split

In [29]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=0) #test_size=0.2 shows that we are going 
#train the data with 80% data and the remaining 20% is tested to trian the model and random_state is not to take random values instead take
#from the dataset

In [31]:
test_x

array([[ 1.5],
       [10.3],
       [ 4.1],
       [ 3.9],
       [ 9.5],
       [ 8.7]])

In [33]:
from sklearn.linear_model import LinearRegression

In [35]:
Lin=LinearRegression()

In [37]:
Lin.fit(train_x,train_y) #this creates our model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [39]:
pred_y=Lin.predict(test_x) #predicting values for test x values

In [41]:
pred_y

array([[ 40748.96184072],
       [122699.62295594],
       [ 64961.65717022],
       [ 63099.14214487],
       [115249.56285456],
       [107799.50275317]])

In [43]:
test_y

array([[ 37731.],
       [122391.],
       [ 57081.],
       [ 63218.],
       [116969.],
       [109431.]])

In [46]:
np.concatenate((test_y,pred_y),axis=1) #adds two arrays into one and axis=1 is for adding them row wise 
#i.e column 1=test_y and column 2=pred_y

array([[ 37731.        ,  40748.96184072],
       [122391.        , 122699.62295594],
       [ 57081.        ,  64961.65717022],
       [ 63218.        ,  63099.14214487],
       [116969.        , 115249.56285456],
       [109431.        , 107799.50275317]])

In [48]:
np.abs(test_y-pred_y) #calculates absolute difference

array([[3017.96184072],
       [ 308.62295594],
       [7880.65717022],
       [ 118.85785513],
       [1719.43714544],
       [1631.49724683]])

In [50]:
np.abs(test_y-pred_y).mean() # mean of all differences

2446.1723690465055

In [52]:
from sklearn import metrics

In [54]:
metrics.mean_absolute_error(test_y,pred_y) #meaan of absolute error

2446.1723690465055

In [55]:
metrics.mean_squared_error(test_y,pred_y) #squared mean error

12823412.298126549